spring:
  profiles:
    active: ${env}

logging:
  level:
    root: "INFO"
    io:
      r2dbc: "INFO"
      netty: "INFO"
    org.springframework:
      r2dbc: "INFO"
  file:
    name: demo-flux
    path: demo-log